# Generates per-id Android app icons + picker previews from source PNGs.
#
# Usage (from repo root):
#   powershell -ExecutionPolicy Bypass -File tool\generate_app_icons.ps1 `
#       -Project . `
#       -Sources "alt=assets\icon\design_alt.png"
#
# For each "id=path" entry this script:
#   1. copies the source  -> assets/icon/design_<id>.png
#   2. writes 96px picker preview -> assets/icon/previews/preview_<id>.png
#   3. writes Android mipmaps -> android/app/src/main/res/mipmap-<dpi>/app_icon_<id>.png
#      (mdpi 48 / hdpi 72 / xhdpi 96 / xxhdpi 144 / xxxhdpi 192)
#
# The DEFAULT icon (id 'default') is NOT handled here: it stays the
# framework-conventional @mipmap/ic_launcher plus the Windows .ico, both
# regenerated by flutter_launcher_icons from pubspec.yaml (image_path).
# Adding a new non-default icon = provide a square PNG, add one "-Sources
# \"id=path\"" entry here (and an AppIconOption in lib/core/app_icon.dart),
# then rerun this script. No platform code changes needed.
param(
  [string]$Project = ".",
  [string[]]$Sources
)

Add-Type -AssemblyName System.Drawing

function Resize-Icon([string]$src, [string]$dest, [int]$size) {
  $bmp = New-Object System.Drawing.Bitmap($src)
  $out = New-Object System.Drawing.Bitmap $size, $size
  $g = [System.Drawing.Graphics]::FromImage($out)
  $g.SmoothingMode = 'HighQuality'
  $g.InterpolationMode = 'HighQualityBicubic'
  $g.PixelOffsetMode = 'HighQuality'
  $g.DrawImage($bmp, 0, 0, $size, $size)
  $out.Save($dest, [System.Drawing.Imaging.ImageFormat]::Png)
  $g.Dispose(); $out.Dispose(); $bmp.Dispose()
}

$previewsDir = Join-Path $Project "assets\icon\previews"
New-Item -ItemType Directory -Force -Path $previewsDir | Out-Null

$densities = @{
  "mdpi"    = 48
  "hdpi"    = 72
  "xhdpi"   = 96
  "xxhdpi"  = 144
  "xxxhdpi" = 192
}

foreach ($entry in $Sources) {
  $parts = $entry.Split('=', 2)
  $id = $parts[0].Trim()
  $src = $parts[1].Trim()
  if (-not $id -or -not (Test-Path $src)) {
    Write-Error "Invalid source entry: $entry"
    continue
  }

  $design = Join-Path $Project "assets\icon\design_$id.png"
  $designFull = (Resolve-Path $design -ErrorAction SilentlyContinue).Path
  $srcFull = (Resolve-Path $src).Path
  if ($srcFull -ne $designFull) {
    Copy-Item $src $design -Force
  }

  $preview = Join-Path $previewsDir "preview_$id.png"
  Resize-Icon $design $preview 96

  foreach ($dpi in $densities.Keys) {
    $dest = Join-Path $Project "android\app\src\main\res\mipmap-$dpi\app_icon_$id.png"
    Resize-Icon $design $dest $densities[$dpi]
  }
  Write-Output "generated id=$id (design+preview+mipmaps)"
}
